default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  host:     localhsot
  username: postgres
  database: #{app_name}_development

test:
  <<: *default
  host:     localhost
  username: postgres
  database: #{app_name}_test

production:
  <<: *default
  host: <%= ENV['APP_DATABASE_HOST'] %>
  database: <%= ENV['APP_DATABASE_NAME'] %>
  username: <%= ENV['APP_DATABASE_USER'] %>
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>